[[product]]
identifier = "budget"
name = "M-Budget Energy Drink"
price = 50

[[product]]
identifier = "duplo"
name = "Kinder Duplo Riegel"
price = 30

[[product]]
identifier = "nocco"
name = "Nocco Energy"
price = 275

[[product]]
identifier = "cola"
name = "Cola Zero"
price = 70

[[product]]
identifier = "noir"
name = "Noir Special Riegel"
price = 100
