[[product]]
identifier = "budget"
name = "M-Budget Energy Drink"
price = 50

[[product]]
identifier = "kong"
name = "Kong Strong Energy Drink"
price = 50

[[product]]
identifier = "cola"
name = "Cola Zero"
price = 70

[[product]]
identifier = "caprisun"
name = "Capri Sonne"
price = 50

[[product]]
identifier = "smirnoff"
name = "Smirnoff Flasche"
price = 235

[[product]]
identifier = "duplo"
name = "Kinder Duplo Riegel"
price = 30

[[product]]
identifier = "noir"
name = "Noir Special Riegel"
price = 100

[[product]]
identifier = "snickers"
name = "Snickers"
price = 50

[[product]]
identifier = "mars"
name = "Mars"
price = 50

[[product]]
identifier = "twix"
name = "Twix"
price = 50

[[product]]
identifier = "farmer"
name = "Farmer Soft"
price = 50

[[product]]
identifier = "brownie"
name = "Farmer Brownie"
price = 100

[[product]]
identifier = "ragusa"
name = "Ragusa 25g"
price = 80

[[product]]
identifier = "babybel"
name = "Mini Babybel"
price = 40

[[product]]
identifier = "hanuta"
name = "Hanuta"
price = 25
