name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Add ssh key
        run: echo "$PRIVATE_KEY" > id_rsa && chmod 600 id_rsa
        env:
          PRIVATE_KEY: ${{ secrets.ssh_key }}
      - name: Add known host
        run: ssh-keyscan -H 46.101.67.169 >> known_hosts
      - name: Build
        run: ssh -i id_rsa -o UserKnownHostsFile=known_hosts jeremy@46.101.67.169 /home/jeremy/.cargo/bin/cargo install -f --git https://github.com/jeremystucki/swissdev-kafi-kaesseli
      - name: Stop service
        run: ssh -i id_rsa -o UserKnownHostsFile=known_hosts jeremy@46.101.67.169 sudo /bin/systemctl stop new_kafi_telegram
      - name: Start service
        run: ssh -i id_rsa -o UserKnownHostsFile=known_hosts jeremy@46.101.67.169 sudo /bin/systemctl start new_kafi_telegram
